version: 0.2

phases:
  pre-build:
    comands:
      - npm install
  build:
    commands:
      - npm run build
      - aws s3 sync ./ s3://nithinv-portfolio/ --cache-control 360000 --expires "2022-06-14T00:00:00Z" --delete

artifacts:
  files:
    - '**/*'
  discard-path: no
  base-directory: build